name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
         
    - name: Read version property
      id: read_property
      uses: christian-draeger/read-properties@1.0.1
      with:
        path: 'version.properties'
        property: 'version'
    
    - name: Application version
      run: echo ${{ steps.read_property.outputs.value }}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 9604670877/git-test-docker-repo:${{ steps.read_property.outputs.value }}
    
    - name: Docker Push
      run: docker push 9604670877/git-test-docker-repo:${{ steps.read_property.outputs.value }}
      
